#Author: Balaji N
#Date: 06-10-2023
#Description: Git Versioning

name: "Git Versioning"
description: "Creating Sematic Version number Major.Minior.Patch"

inputs:
  git-tool-latest:
    required: false
    description: "Use latest Git Tool version"
    default: 'false'
  pre-release:
    required: false
    description: "Enable pre-release for GitVersion"
    default: 'false'
  use-config-file:
    required: false
    description: "Use config file to determine version"
    default: 'false'
  additional-arguments:
    required: false
    description: "Additional command line arguments to pass to the GitVersion cmd."
  
outputs:
  Major:
    value: ${{ steps.gitversion.outputs.major }}
    description: ''
  Minor:
    value: ${{ steps.gitversion.outputs.minor }}
    description: ''
  Patch:
    value: ${{ steps.gitversion.outputs.patch }}
    description: ''
  PreReleaseTag:
    value: ${{ steps.gitversion.outputs.preReleaseTag }}
    description: ''
  PreReleaseTagWithDash:
    value: ${{ steps.gitversion.outputs.preReleaseTagWithDash }}
    description: ''
  PreReleaseLabel:
    value: ${{ steps.gitversion.outputs.preReleaseLabel }}
    description: ''
  PreReleaseNumber:
    value: ${{ steps.gitversion.outputs.preReleaseNumber }}
    description: ''
  WeightedPreReleaseNumber:
    value: ${{ steps.gitversion.outputs.weightedPreReleaseNumber }}
    description: ''
  BuildMetaData:
    value: ${{ steps.gitversion.outputs.buildMetaData }}
    description: ''
  BuildMetaDataPadded:
    value: ${{ steps.gitversion.outputs.buildMetaDataPadded }}
    description: ''
  FullBuildMetaData:
    value: ${{ steps.gitversion.outputs.fullBuildMetaData }}
    description: ''
  MajorMinorPatch:
    value: ${{ steps.gitversion.outputs.majorMinorPatch }}
    description: ''
  SemVer:
    value: ${{ steps.gitversion.outputs.semVer }}
    description: ''
  LegacySemVer:
    value: ${{ steps.gitversion.outputs.legacySemVer }}
    description: ''
  LegacySemVerPadded:
    value: ${{ steps.gitversion.outputs.legacySemVerPadded }}
    description: ''
  AssemblySemVer:
    value: ${{ steps.gitversion.outputs.assemblySemVer }}
    description: ''
  AssemblySemFileVer:
    value: ${{ steps.gitversion.outputs.assemblySemFileVer }}
    description: ''
  FullSemVer:
    value: ${{ steps.gitversion.outputs.fullSemVer }}
    description: ''
  InformationalVersion:
    value: ${{ steps.gitversion.outputs.informationalVersion }}
    description: ''
  BranchName:
    value: ${{ steps.gitversion.outputs.branchName }}
    description: ''
  EscapedBranchName:
    value: ${{ steps.gitversion.outputs.escapedBranchName }}
    description: ''
  Sha:
    value: ${{ steps.gitversion.outputs.sha }}
    description: ''
  ShortSha:
    value: ${{ steps.gitversion.outputs.shortSha }}
    description: ''
  NuGetVersionV2:
    value: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    description: ''
  NuGetVersion:
    value: ${{ steps.gitversion.outputs.nuGetVersion }}
    description: ''
  NuGetPreReleaseTagV2:
    value: ${{ steps.gitversion.outputs.nuGetPreReleaseTagV2 }}
    description: ''
  NuGetPreReleaseTag:
    value: ${{ steps.gitversion.outputs.nuGetPreReleaseTag }}
    description: ''
  VersionSourceSha:
    value: ${{ steps.gitversion.outputs.versionSourceSha }}
    description: ''
  CommitsSinceVersionSource:
    value: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}
    description: ''
  CommitsSinceVersionSourcePadded:
    value: ${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}
    description: ''
  UncommittedChanges:
    value: ${{ steps.gitversion.outputs.uncommittedChanges }}
    description: ''
  CommitDate:
    value: ${{ steps.gitversion.outputs.commitDate }}
    description: ''

runs:
  using: "composite"
  steps:

  - name: 'Install GitVersion'
    uses: gittools/actions/gitversion/setup@v4.1.0
    with:
      versionSpec: '6.x'
      includePrerelease: ${{ inputs.pre-release }}
      preferLatestVersion: ${{ inputs.git-tool-latest }}
  
  - name: "Determine Version"
    id: gitversion
    uses: gittools/actions/gitversion/command@v4.1.0
    with:
      arguments: ${{ inputs.additional-arguments }} /output buildserver
  
  - name: Display GitVersion outputs (step output)
    shell: 'bash'
    run: |
      echo "Major: ${{ env.major }}"
      echo "Minor: ${{ env.minor }}"
      echo "Patch: ${{ env.patch }}"
      echo "PreReleaseTag: ${{ env.preReleaseTag }}"
      echo "PreReleaseTagWithDash: ${{ env.preReleaseTagWithDash }}"
      echo "PreReleaseLabel: ${{ env.preReleaseLabel }}"
      echo "PreReleaseNumber: ${{ env.preReleaseNumber }}"
      echo "WeightedPreReleaseNumber: ${{ env.weightedPreReleaseNumber }}"
      echo "BuildMetaData: ${{ env.buildMetaData }}"
      echo "BuildMetaDataPadded: ${{ env.buildMetaDataPadded }}"
      echo "FullBuildMetaData: ${{ env.fullBuildMetaData }}"
      echo "MajorMinorPatch: ${{ env.majorMinorPatch }}"
      echo "SemVer: ${{ env.semVer }}"
      echo "LegacySemVer: ${{ env.legacySemVer }}"
      echo "LegacySemVerPadded: ${{ env.legacySemVerPadded }}"
      echo "AssemblySemVer: ${{ env.assemblySemVer }}"
      echo "AssemblySemFileVer: ${{ env.assemblySemFileVer }}"
      echo "FullSemVer: ${{ env.fullSemVer }}"
      echo "InformationalVersion: ${{ env.informationalVersion }}"
      echo "BranchName: ${{ env.branchName }}"
      echo "EscapedBranchName: ${{ env.escapedBranchName }}"
      echo "Sha: ${{ env.sha }}"
      echo "ShortSha: ${{ env.shortSha }}"
      echo "NuGetVersionV2: ${{ env.nuGetVersionV2 }}"
      echo "NuGetVersion: ${{ env.nuGetVersion }}"
      echo "NuGetPreReleaseTagV2: ${{ env.nuGetPreReleaseTagV2 }}"
      echo "NuGetPreReleaseTag: ${{ env.nuGetPreReleaseTag }}"
      echo "VersionSourceSha: ${{ env.versionSourceSha }}"
      echo "CommitsSinceVersionSource: ${{ env.commitsSinceVersionSource }}"
      echo "CommitsSinceVersionSourcePadded: ${{ env.commitsSinceVersionSourcePadded }}"
      echo "UncommittedChanges: ${{ env.uncommittedChanges }}"
      echo "CommitDate: ${{ env.commitDate }}"

  - name: Display GitVersion outputs (step output with prefix)
    shell: 'bash'
    run: |
      echo "Major: ${{ env.GitVersion_Major }}"
      echo "Minor: ${{ env.GitVersion_Minor }}"
      echo "Patch: ${{ env.GitVersion_Patch }}"
      echo "PreReleaseTag: ${{ env.GitVersion_PreReleaseTag }}"
      echo "PreReleaseTagWithDash: ${{ env.GitVersion_PreReleaseTagWithDash }}"
      echo "PreReleaseLabel: ${{ env.GitVersion_PreReleaseLabel }}"
      echo "PreReleaseNumber: ${{ env.GitVersion_PreReleaseNumber }}"
      echo "WeightedPreReleaseNumber: ${{ env.GitVersion_WeightedPreReleaseNumber }}"
      echo "BuildMetaData: ${{ env.GitVersion_BuildMetaData }}"
      echo "BuildMetaDataPadded: ${{ env.GitVersion_BuildMetaDataPadded }}"
      echo "FullBuildMetaData: ${{ env.GitVersion_FullBuildMetaData }}"
      echo "MajorMinorPatch: ${{ env.GitVersion_MajorMinorPatch }}"
      echo "SemVer: ${{ env.GitVersion_SemVer }}"
      echo "LegacySemVer: ${{ env.GitVersion_LegacySemVer }}"
      echo "LegacySemVerPadded: ${{ env.GitVersion_LegacySemVerPadded }}"
      echo "AssemblySemVer: ${{ env.GitVersion_AssemblySemVer }}"
      echo "AssemblySemFileVer: ${{ env.GitVersion_AssemblySemFileVer }}"
      echo "FullSemVer: ${{ env.GitVersion_FullSemVer }}"
      echo "InformationalVersion: ${{ env.GitVersion_InformationalVersion }}"
      echo "BranchName: ${{ env.GitVersion_BranchName }}"
      echo "EscapedBranchName: ${{ env.GitVersion_EscapedBranchName }}"
      echo "Sha: ${{ env.GitVersion_Sha }}"
      echo "ShortSha: ${{ env.GitVersion_ShortSha }}"
      echo "NuGetVersionV2: ${{ env.GitVersion_NuGetVersionV2 }}"
      echo "NuGetVersion: ${{ env.GitVersion_NuGetVersion }}"
      echo "NuGetPreReleaseTagV2: ${{ env.GitVersion_NuGetPreReleaseTagV2 }}"
      echo "NuGetPreReleaseTag: ${{ env.GitVersion_NuGetPreReleaseTag }}"
      echo "VersionSourceSha: ${{ env.GitVersion_VersionSourceSha }}"
      echo "CommitsSinceVersionSource: ${{ env.GitVersion_CommitsSinceVersionSource }}"
      echo "CommitsSinceVersionSourcePadded: ${{ env.GitVersion_CommitsSinceVersionSourcePadded }}"
      echo "UncommittedChanges: ${{ env.GitVersion_UncommittedChanges }}"
      echo "CommitDate: ${{ env.GitVersion_CommitDate }}"