name: "Git Versioning"
description: "Creating Sematic Versioning using GitVersion"

inputs:
  git-tool-latest:
    required: false
    description: "Use latest Git Tool version"
    default: 'false'
  pre-release:
    required: false
    description: "Enable pre-release for GitVersion"
    default: 'false'
  use-config-file:
    required: false
    description: "Use config file to determine version"
    default: 'false'
  override-config:
    required: false
    description: "Provide override config for GitVersion (e.g., tag-prefix=v)"
  
outputs:
  Major:
    value: ${{ steps.output-gitversion.outputs.major }}
    description: ''
  Minor:
    value: ${{ steps.output-gitversion.outputs.minor }}
    description: ''
  Patch:
    value: ${{ steps.output-gitversion.outputs.patch }}
    description: ''
  PreReleaseTag:
    value: ${{ steps.output-gitversion.outputs.preReleaseTag }}
    description: ''
  PreReleaseTagWithDash:
    value: ${{ steps.output-gitversion.outputs.preReleaseTagWithDash }}
    description: ''
  PreReleaseLabel:
    value: ${{ steps.output-gitversion.outputs.preReleaseLabel }}
    description: ''
  PreReleaseNumber:
    value: ${{ steps.output-gitversion.outputs.preReleaseNumber }}
    description: ''
  WeightedPreReleaseNumber:
    value: ${{ steps.output-gitversion.outputs.weightedPreReleaseNumber }}
    description: ''
  BuildMetaData:
    value: ${{ steps.output-gitversion.outputs.buildMetaData }}
    description: ''
  FullBuildMetaData:
    value: ${{ steps.output-gitversion.outputs.fullBuildMetaData }}
    description: ''
  MajorMinorPatch:
    value: ${{ steps.output-gitversion.outputs.majorMinorPatch }}
    description: ''
  SemVer:
    value: ${{ steps.output-gitversion.outputs.semVer }}
    description: ''
  AssemblySemVer:
    value: ${{ steps.output-gitversion.outputs.assemblySemVer }}
    description: ''
  AssemblySemFileVer:
    value: ${{ steps.output-gitversion.outputs.assemblySemFileVer }}
    description: ''
  FullSemVer:
    value: ${{ steps.output-gitversion.outputs.fullSemVer }}
    description: ''
  InformationalVersion:
    value: ${{ steps.output-gitversion.outputs.informationalVersion }}
    description: ''
  BranchName:
    value: ${{ steps.output-gitversion.outputs.branchName }}
    description: ''
  EscapedBranchName:
    value: ${{ steps.output-gitversion.outputs.escapedBranchName }}
    description: ''
  Sha:
    value: ${{ steps.output-gitversion.outputs.sha }}
    description: ''
  ShortSha:
    value: ${{ steps.output-gitversion.outputs.shortSha }}
    description: ''
  VersionSourceSha:
    value: ${{ steps.output-gitversion.outputs.versionSourceSha }}
    description: ''
  CommitsSinceVersionSource:
    value: ${{ steps.output-gitversion.outputs.commitsSinceVersionSource }}
    description: ''
  UncommittedChanges:
    value: ${{ steps.output-gitversion.outputs.uncommittedChanges }}
    description: ''
  CommitDate:
    value: ${{ steps.output-gitversion.outputs.commitDate }}
    description: ''

runs:
  using: "composite"
  steps:

  - name: 'Install GitVersion'
    uses: gittools/actions/gitversion/setup@v4.1.0
    with:
      versionSpec: '6.x'
      includePrerelease: ${{ inputs.pre-release }}
      preferLatestVersion: ${{ inputs.git-tool-latest }}
  
  - name: "Determine Version"
    id: gitversion
    uses: gittools/actions/gitversion/execute@v4.1.0
    with:
      overrideConfig: |
        ${{ inputs.override-config }}
  
  - name: Display GitVersion outputs (step output with prefix)
    shell: 'bash'
    run: |
      echo "Major: ${{ steps.gitversion.outputs.Major }}"
      echo "Minor: ${{ steps.gitversion.outputs.Minor }}"
      echo "Patch: ${{ steps.gitversion.outputs.Patch }}"
      echo "PreReleaseTag: ${{ steps.gitversion.outputs.PreReleaseTag }}"
      echo "PreReleaseTagWithDash: ${{ steps.gitversion.outputs.PreReleaseTagWithDash }}"
      echo "PreReleaseLabel: ${{ steps.gitversion.outputs.PreReleaseLabel }}"
      echo "PreReleaseNumber: ${{ steps.gitversion.outputs.PreReleaseNumber }}"
      echo "WeightedPreReleaseNumber: ${{ steps.gitversion.outputs.WeightedPreReleaseNumber }}"
      echo "BuildMetaData: ${{ steps.gitversion.outputs.BuildMetaData }}"
      echo "FullBuildMetaData: ${{ steps.gitversion.outputs.FullBuildMetaData }}"
      echo "MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
      echo "SemVer: ${{ steps.gitversion.outputs.SemVer }}"
      echo "AssemblySemVer: ${{ steps.gitversion.outputs.AssemblySemVer }}"
      echo "AssemblySemFileVer: ${{ steps.gitversion.outputs.AssemblySemFileVer }}"
      echo "FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}"
      echo "InformationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}"
      echo "BranchName: ${{ steps.gitversion.outputs.BranchName }}"
      echo "EscapedBranchName: ${{ steps.gitversion.outputs.EscapedBranchName }}"
      echo "Sha: ${{ steps.gitversion.outputs.Sha }}"
      echo "ShortSha: ${{ steps.gitversion.outputs.ShortSha }}"
      echo "VersionSourceSha: ${{ steps.gitversion.outputs.VersionSourceSha }}"
      echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
      echo "UncommittedChanges: ${{ steps.gitversion.outputs.UncommittedChanges }}"
      echo "CommitDate: ${{ steps.gitversion.outputs.CommitDate }}"

  - name: Output GitVersion results
    id: output-gitversion
    shell: pwsh
    run: |
      "major=${{ steps.gitversion.outputs.Major }}" >> $env:GITHUB_OUTPUT
      "minor=${{ steps.gitversion.outputs.Minor }}" >> $env:GITHUB_OUTPUT
      "patch=${{ steps.gitversion.outputs.Patch }}" >> $env:GITHUB_OUTPUT
      "preReleaseTag=${{ steps.gitversion.outputs.PreReleaseTag }}" >> $env:GITHUB_OUTPUT
      "preReleaseTagWithDash=${{ steps.gitversion.outputs.PreReleaseTagWithDash }}" >> $env:GITHUB_OUTPUT
      "preReleaseLabel=${{ steps.gitversion.outputs.PreReleaseLabel }}" >> $env:GITHUB_OUTPUT
      "preReleaseNumber=${{ steps.gitversion.outputs.PreReleaseNumber }}" >> $env:GITHUB_OUTPUT
      "weightedPreReleaseNumber=${{ steps.gitversion.outputs.WeightedPreReleaseNumber }}" >> $env:GITHUB_OUTPUT
      "buildMetaData=${{ steps.gitversion.outputs.BuildMetaData }}" >> $env:GITHUB_OUTPUT
      "fullBuildMetaData=${{ steps.gitversion.outputs.FullBuildMetaData }}" >> $env:GITHUB_OUTPUT
      "majorMinorPatch=${{ steps.gitversion.outputs.MajorMinorPatch }}" >> $env:GITHUB_OUTPUT
      "semVer=${{ steps.gitversion.outputs.SemVer }}" >> $env:GITHUB_OUTPUT
      "assemblySemVer=${{ steps.gitversion.outputs.AssemblySemVer }}" >> $env:GITHUB_OUTPUT
      "assemblySemFileVer=${{ steps.gitversion.outputs.AssemblySemFileVer }}" >> $env:GITHUB_OUTPUT
      "fullSemVer=${{ steps.gitversion.outputs.FullSemVer }}" >> $env:GITHUB_OUTPUT
      "informationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}" >> $env:GITHUB_OUTPUT
      "branchName=${{ steps.gitversion.outputs.BranchName }}" >> $env:GITHUB_OUTPUT
      "escapedBranchName=${{ steps.gitversion.outputs.EscapedBranchName }}" >> $env:GITHUB_OUTPUT
      "sha=${{ steps.gitversion.outputs.Sha }}" >> $env:GITHUB_OUTPUT
      "shortSha=${{ steps.gitversion.outputs.ShortSha }}" >> $env:GITHUB_OUTPUT
      "versionSourceSha=${{ steps.gitversion.outputs.VersionSourceSha }}" >> $env:GITHUB_OUTPUT
      "commitsSinceVersionSource=${{ steps.gitversion.outputs.CommitsSinceVersionSource }}" >> $env:GITHUB_OUTPUT
      "uncommittedChanges=${{ steps.gitversion.outputs.UncommittedChanges }}" >> $env:GITHUB_OUTPUT
      "commitDate=${{ steps.gitversion.outputs.CommitDate }}" >> $env:GITHUB_OUTPUT
      Write-Host "GitVersion outputs set."
