name: 'Generate New Git Tags'
run-name: New ${{ github.ref_name == 'main' && 'Release' || 'Prerelease' }} Version

on:
  push:
    branches: ['main', 'develop', 'release/*', 'hotfix/*', 'release', 'rc*' ]

permissions:
  id-token: write
  contents: write
  pull-requests: read

jobs:
  CreateNextRelease:
    name: 'Creating Next Github Release'
    uses: ./.github/workflows/push-github-release.yml
    with:
      create-major-minor: ${{ github.ref_name == 'main' }}
      create-major: ${{ github.ref_name == 'main' }}
      tag-prefix: 'v'
      prerelease: ${{ github.ref_name != 'main' }}
      generate-notes: ${{ github.ref_name == 'main' }}

