name: Testing versioning
on:
  push

jobs:
  test-versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Git Version
      uses: ./.github/actions/git-version
      id: git-version
      with:
        git-tool-latest: 'true'
        use-config-file: 'true'
        pre-release: ${{ github.ref_name != 'main' && 'true' || 'false' }}
        additional-arguments: '/overrideconfig tag-prefix=v /b ${{ github.ref_name }}'
